on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
name: Build robot
jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set SSH key
        if: (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master')
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Add known host key
        run: ssh-keyscan javacard.pro >> ~/.ssh/known_hosts
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: maven
      - name: Compile and verify
        run: ./mvnw -U -B -T1C verify
      - name: Deploy snapshot
        if: (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/next' || github.ref == 'refs/heads/master')
        run: ./mvnw -B deploy
